### ISSUE TITLE
Recursive call or synchronization error

### ISSUE THREAD

**Issue by askielboe** [RxSwiftCommunity/RxCoreMotion#14]
After updating to [RxSwift 3.4.1](https://github.com/ReactiveX/RxSwift/releases/tag/3.4.1) I'm getting the following warning (fatal error in #DEBUG mode):

    fatal error: Warning: Recursive call or synchronization error!: file /Users/askielboe/work/DeviceMotion/Pods/RxSwift/RxSwift/Observables/Create.swift, line 43
    2017-05-22 10:05:00.035696+0200 DeviceMotion[3500:779034] fatal error: Warning: Recursive call or synchronization error!: file /Users/askielboe/work/DeviceMotion/Pods/RxSwift/RxSwift/Observables/Create.swift, line 43

I can reproduce this in a clean Xcode project, by allowing the device motion subscription to run for a while, using the following code:

```Swift
struct MotionManager {
    static func motionObservable() -> Observable<CMDeviceMotion> {
        return CMMotionManager.rx.manager()
            .flatMapLatest { manager in
                manager.deviceMotion ?? Observable.empty()
            }
    }
}

class ViewController: UIViewController {

    let disposeBag = DisposeBag()

    override func viewDidLoad() {
        super.viewDidLoad()

        MotionManager.motionObservable()
            .buffer(timeSpan: 1, count: 0, scheduler: MainScheduler.instance)
            .subscribe(onNext: { deviceMotion in
                NSLog("Next device motion.")
            })
            .disposed(by: disposeBag)
    }
}
```

The error is also reproduced in the `RxCoreMotionExample` project on the [current master HEAD](https://github.com/RxSwiftCommunity/RxCoreMotion/commit/76afa1747a3385313d46f0932b8f77daafbd8357) by navigating to the `DeviceMotionViewController`, and letting the subscription run for a few minutes.

#### Related RxSwift issues:
 1. https://github.com/ReactiveX/RxSwift/issues/1202
 2. https://github.com/ReactiveX/RxSwift/issues/1201
 3. https://github.com/ReactiveX/RxSwift/issues/1192

#### My environment:
```
macOS 10.12.4
Xcode 8.3.2
iOS 10.3.2
cocoapods 1.2.1
RxSwift 3.4.1
RxCoreMotion 1.1.1
iPhone 7
```

**Comment by freak4pc** [comment]
The stack trace Pinpoint the issue at [RxCoreMotion.swift:L61](https://github.com/RxSwiftCommunity/RxCoreMotion/blob/master/Pod/Classes/RxCoreMotion.swift#L61) 

The trace is super-slim here so I have no real idea what causes this. I imagine its because values are pushed extremely quickly (and in bulk) to the Observer, but this smells like a bug to me. 

Adding a NSRecursiveLock around around it seems to solve it but I'm not sure if its a bandaid or a correct solution so would defer to @kzaher here, e.g. 

```swift
motionManager.startGyroUpdates(to: OperationQueue(), withHandler: { (data: CMGyroData?, error: Error?) -> Void in
    let _lock = NSRecursiveLock(); defer { _lock.unlock() }
    guard let data = data else {
        return
    }
    _lock.lock()
    observer.on(.next(data.rotationRate))
})
```

**Comment by freak4pc** [comment]
Ok, I take it back. The recursive lock got it to run for much longer but eventually it still crashed with the same issue. I'm not 100% sure what's the issue but I hope Krunoslav could share his thoughts.

**Comment by freak4pc** [comment]
@askielboe I pushed a PR to fix this, would you mind trying it locally to see if it resolve your issue ?

**Comment by askielboe** [comment]
Seems to be working. Thanks for responding quickly to this. 👍 

Is there a reason you've only added `maxConcurrentOperationCount = 1` to the gyro updates? I guess you'll need to add it for for all the observables. :)

While testing this I found a few issues with the Examples project which I've fixed here: https://github.com/RxSwiftCommunity/RxCoreMotion/pull/16.

**Comment by freak4pc** [comment]
@askielboe  Yeah. This new error from RxSwift 3.4 and above means (in this case): there are two values being emitted at the same time. To prevent this we make OperationQueue serial by declaring it can only have 1 concurrent task and by that one concurrent emission.

**Comment by askielboe** [comment]
Excellent. Thanks for fixing this!
